- hosts: appservers
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

